version: '3.3'

services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php81
    depends_on:
      - &dbhost postgres
    image: php:8.2-apache
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:8000
  # db:
  #   container_name: mysql8
  #   image: mysql:8.0
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: &dbname iai_php
  #     MYSQL_DATABASE: *dbname
  #     MYSQL_USER: &dbuser myuser
  #     MYSQL_PASSWORD: &dbpwd monpassword
  #   volumes:
  #     - ./db:/var/lib/mysql
  #   ports:
  #     - 3306:3306
  # phpmya:
  #   image: phpmyadmin/phpmyadmin:latest
  #   container_name: phpmyadmin
  #   environment:
  #     PMA_ARBITRARY: 1
  #     PMA_HOST: *dbhost
  #     PMA_USER: *dbuser
  #     PMA_PASSWORD: *dbpwd
  #     UPLOAD_LIMIT: 20M
  #   ports:
  #     - 8899:80
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: &dbuser myuser
      POSTGRES_PASSWORD: &dbpwd monpassword
      POSTGRES_DB: &dbname iai_php
      PGDATA: /data/postgres
    volumes:
      - ./pg_db:/data/postgres
    ports:
      - 5434:5432
    restart: unless-stopped
  pgadmin:
     container_name: pgadmin_container
     image: dpage/pgadmin4
     environment:
       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
       PGADMIN_CONFIG_SERVER_MODE: 'False'
     volumes:
       - ./pgadmin:/var/lib/pgadmin
     ports:
       - 5050:80
     restart: unless-stopped
